Repository GoOnThat/GoOnThat, pull requests merged in 2023-07, with the labels that each got.

#4 게시판 목록, 글쓰기, 글조회 html 구현
  src/main/resources/static/css/board.css
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/write.html
Labels: feature

#22 Feature/board dto and repository
  build.gradle
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/entity/Entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/Vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/query/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/query/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/query/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/query/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/application/dto/BoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/application/dto/BoardListDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/application/dto/BoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/application/service/BoardService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/domain/aggregate/entity/Entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/domain/repository/BoardRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/command/infra/repository/BoardImplRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/login/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/login/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/login/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/login/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/domain/aggregate/entity/Entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/domain/aggregate/vo/Vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/domain/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/domain/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/query/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/query/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/query/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/member/query/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/domain/aggregate/entity/Entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/domain/aggregate/vo/Vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/domain/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/domain/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/mypage/command/infra/service/Service.java
Labels: feature

#25 07-14 병합용
  README.md
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/entity/Board.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardCategory.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardContent.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardDate.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardDeleteYn.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardHits.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardTitle.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/BoardWriter.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/board/command/domain/aggregate/vo/Vo.java
  src/main/resources/application.properties
Labels: feature

#32 07-14 작성자 변경, 폴더구조 변경
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/domain/aggregate/entity/Comment.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/domain/repository/CommentRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/coment/commnad/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/commnad/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/query/infra/Infra.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/commnad/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/infra/Infra.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoard.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardCategory.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardContent.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardDate.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardDeleteYn.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardTitle.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardWriter.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/commnad/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/query/infra/Infra.java
Labels: refactor

#33 BoardWriter 자료형 변경 완료
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardListDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardWriter.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/repository/FreeBoardRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/mapper/FreeBoardMapper.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/infra/repository/FreeBoardRepository.java
Labels: feature

#45 COMMENT ENTITY 구현
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/entity/Comment.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/CommentChildren.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/CommentContent.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/CommentDate.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/CommentDeleteYn.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/CommentParent.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/CommentWriter.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/query/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/query/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/query/query/infra/Infra.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoard.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardCategory.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardContent.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardDate.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardDeleteYn.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardHits.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardTitle.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/vo/BoardWriter.java
Labels: feature

#56 Test2
  README.md
  build.gradle
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/dto/FreeBoardCommentReadDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/entity/FreeBoardComment.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/common/MainController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/config/SecurityConfig.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/declaration/query/infra/Infra.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/domain/user/MetaUser.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/domain/user/MetaUserRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/infra/Infra.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardListDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardUpdateDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/repository/FreeBoardPostRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/domain/service/service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/query/infra/Infra.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/write.html
  src/main/resources/templates/index.html
  src/test/java/com/ohgiraffers/goonthatbackend/GoOnThatBackendApplicationTests.java
Labels: feature

#61 Feature/feeboard delete
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDeleteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardEditDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/AccessService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/AccessImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit.html
Labels: feature

#65 Feature/commenthj2
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/controller/FreeBoardCommentController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/dto/FreeBoardCommentReadDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/service/FreeBoardCommentService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/repository/CommentRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/repository/FreeBoardCommentRepository.java
  src/main/resources/templates/board/detail.html
Labels: feature

#66 07.22 CRUD U 구현, Exception 처리 (BACK)
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/AccessService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/AccessImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
Labels: feature

#71 댓글 조회 기능 구현 #64
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/controller/FreeBoardCommentController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/service/FreeBoardCommentService.java
  src/main/resources/templates/board/detail.html
Labels: feature, refactor

#73 Feature/getboardcomment
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/dto/FreeBoardCommentReadDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/repository/FreeBoardCommentRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardListDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
Labels: refactor

#77 댓글 삭제 기능 구현 #75
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/controller/FreeBoardCommentController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/dto/FreeBoardCommentReadDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/service/FreeBoardCommentService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/entity/FreeBoardComment.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/AccessService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/AccessImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
Labels: feature

#80 Feature/file up
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/common/MD5Generator.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/controller/FileController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/dto/FileDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/service/FileService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/domain/aggregate/entity/File.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/domain/service/FileServiceImpl.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/infra/repository/FileRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/write.html
  src/test/java/com/ohgiraffers/goonthatbackend/metamate/ApplicationTests.java
Labels: enhancement, feature

#81 0724 게시판 리스트 페이징 구현완료, 댓글 조회(view) 변경, 조회수 구현
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardListDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/repository/FreeBoardPostRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/list.html
Labels: feature

#84 댓글 수정 기능 구현 #83
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/controller/FreeBoardCommentController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/service/FreeBoardCommentService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/aggregate/entity/FreeBoardComment.java
  src/main/resources/templates/board/detail.html
Labels: feature

#85 Feature/search board paging board
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/repository/FreeBoardPostRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/list.html
Labels: feature

#89 Feature/board/categorysearch
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardEditDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/repository/FreeBoardPostRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/AccessImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/write.html
Labels: feature

#91 Feature/file multiboard
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/domain/repository/FreeBoardCommentRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/controller/FileController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/dto/FileDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/application/service/FileService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/domain/aggregate/vo/vo.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/infra/repository/FileRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/file/query/infra/Infra.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardEditDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/application/controller/MultiFilesController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/application/dto/MultiFilesReadDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/application/dto/MultiFilesWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/application/service/MultiFilesService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/domain/aggregate/entity/MultiFiles.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/infra/repository/MultiFilesRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/infra/service/Service.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/query/infra/Infra.java
  src/main/resources/application.yml
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/edit.html
  src/main/resources/templates/board/write.html
Labels: feature

#95 댓글 유효성 검사 구현 #94
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/controller/FreeBoardCommentController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/dto/FreeBoardCommentWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/comment/command/application/service/FreeBoardCommentService.java
  src/main/resources/templates/board/detail.html
Labels: feature, refactor

#102 좋아요 추가, 삭제, 카운트 기능 #99 #100 #101
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardDetailDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/controller/Controller.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/controller/LikeController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/dto/DTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/application/dto/LikeBoardDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/domain/aggregate/entity/Like.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/domain/aggregate/entity/entity.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/infra/repository/LikeRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/infra/repository/Repository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/infra/service/LikeService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/like/command/infra/service/Service.java
  src/main/resources/templates/board/detail.html
Labels: feature

#104 Feature/finalboard
  README.md
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/controller/FreeBoardController.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/dto/FreeBoardWriteDTO.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/application/service/FreeBoardPostService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/aggregate/entity/FreeBoardPost.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/repository/FreeBoardPostRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/freeboard/command/domain/service/FreeBoardPostImplService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/application/service/MultiFilesService.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/domain/aggregate/entity/MultiFiles.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/command/infra/repository/MultiFilesRepository.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/query/application/Application.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/query/domain/Domian.java
  src/main/java/com/ohgiraffers/goonthatbackend/metamate/multifile/query/infra/Infra.java
  src/main/resources/templates/board/detail.html
  src/main/resources/templates/board/list.html
  src/main/resources/templates/board/write.html
Labels: feature
